import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL("https://eneelectrical.com"),
  title: "ENE Electrical",
  description: "Generated by AI Studio",
};

// Sitewide JSON-LD (Organization/LocalBusiness + WebSite). Injected as a literal
// object by project-writer.ts from verified facts only — never from AI output —
// so this can never contain a fabricated address, phone, or credential.
const SITEWIDE_SCHEMA = [{"@context":"https://schema.org","@type":"LocalBusiness","name":"ENE Electrical","url":"https://eneelectrical.com","address":{"@type":"PostalAddress","streetAddress":"Katy, TX 77494"},"areaServed":"Houston and Katy, TX metro including Katy, Energy Corridor, Southwest Houston, Cinco Ranch, Fulshear, Memorial, Spring Branch, Westchase, Brookshire, Richmond, TX"},{"@context":"https://schema.org","@type":"WebSite","name":"ENE Electrical","url":"https://eneelectrical.com"}];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white text-gray-900 antialiased">
        {SITEWIDE_SCHEMA.map((schema: Record<string, unknown>, i: number) => (
          <script
            key={i}
            type="application/ld+json"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
          />
        ))}
        {children}
      </body>
    </html>
  );
}
